version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research_db
    ports:
      - '5432:5432'
  redis:
    image: redis:6
    ports:
      - '6379:6379'
  backend:
    build: .
    depends_on:
      - db
      - redis
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/research_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NEWS_API_KEY: ${NEWS_API_KEY}
    ports:
      - '3000:3000'

  worker:
    build: .
    depends_on:
      - db
      - redis
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: research_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NEWS_API_KEY: ${NEWS_API_KEY}
    command: ["npm", "run", "worker"]